# Generated by Django 5.2.6 on 2025-09-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant_type', models.CharField(choices=[('italian', 'Italian'), ('mexican', 'Mexican'), ('chinese', 'Chinese'), ('american', 'American'), ('french', 'French'), ('indian', 'Indian'), ('thai', 'Thai')], max_length=20)),
                ('date_opened', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='restaurant.restaurant')),
            ],
        ),
    ]
